#pragma once

#include <cstddef>
#include <cstdint>
#include <expected>
#include <span>

namespace ch38::soft_shadows
{

inline constexpr std::uint32_t kMaxAreaLightSamples = 1'000'000U;

struct Float2 final
{
    float x{};
    float y{};
};

// Row-major, linear normalized light-space depths. A stored zero is a valid
// near-plane sample, NOT an out-of-frustum sentinel.
struct ShadowMap final
{
    std::span<float const> depths{};
    std::uint32_t width{};
    std::uint32_t height{};
};

struct Receiver final
{
    Float2 uv{};
    float depth{};
    float bias{};
};

enum class SoftShadowError : std::uint8_t
{
    NonFiniteValue,
    InvalidDepth,
    InvalidMap,
    InvalidRadius,
    InvalidGeometry,
    InvalidSampleCount,
    InvalidConfidence,
};

struct Comparison final
{
    bool lit{};
    bool compared{};
};

struct PcssParameters final
{
    float lightRadiusTexels{4.0F};
    float lightNearDepth{0.01F};
    std::uint32_t maxRadiusTexels{16U};
};

struct PcssResult final
{
    float visibility{1.0F};
    float averageBlockerDepth{};
    std::uint32_t blockerCount{};
    std::uint32_t searchRadiusTexels{};
    std::uint32_t filterRadiusTexels{};
    bool penumbraClamped{};
    bool degenerateBlockerDepth{};
    bool compared{};
};

// Projected circular blocker silhouettes in the unit-area light disk's plane.
// A point sample is occluded if it lies inside any silhouette. This 2D
// coverage model does NOT trace 3D rays or represent general 3D occluders.
struct DiskBlocker final
{
    Float2 center{};
    float radius{};
};

struct VisibilityEstimate final
{
    float visibility{};
    float sampleVariance{};
    float standardError{};
    float confidenceHalfWidth{};
    std::uint32_t sampleCount{};
    std::uint32_t visibleCount{};
};

// Returns lit without comparison for any coordinate/depth outside [0,1].
// Non-finite inputs and invalid in-frustum data are reported, never silently
// interpreted as an outside receiver. Equality is lit; bias subtracts from
// receiver depth. All stored shadow-map depths must be finite and in [0,1].
[[nodiscard]] std::expected<Comparison, SoftShadowError> CompareDepth(Receiver receiver, float storedDepth) noexcept;

// Nearest texel is floor(uv * dimensions), clamped at the inclusive UV edge.
// A square (2r+1)^2 PCF kernel treats each out-of-map tap as lit (depth 1);
// border taps keep their full kernel weight and do not repeat the edge texel.
[[nodiscard]] std::expected<float, SoftShadowError> PercentageCloserFilter(ShadowMap map, Receiver receiver,
                                                                           std::uint32_t radiusTexels) noexcept;

// PCSS-style square blocker search followed by PCF. Search radius approximates
// lightRadius * (receiverDepth-near)/receiverDepth; filter radius approximates
// lightRadius * (receiverDepth-averageBlocker)/averageBlocker. Both are capped
// by maxRadiusTexels (1..32); these are texel-space heuristics, NOT exact
// physical area-light integration. At blocker depth zero the filter saturates
// at maxRadiusTexels instead of dividing by zero. Out-of-map blocker-search
// taps are lit border (depth 1) and therefore cannot become blockers.
[[nodiscard]] std::expected<PcssResult, SoftShadowError> EstimatePcss(ShadowMap map, Receiver receiver,
                                                                      PcssParameters parameters = {}) noexcept;

// sampleCount must be in [1, kMaxAreaLightSamples]; exceeding that bound
// reports InvalidSampleCount rather than running an unbounded loop.
// Uniform disk samples generated by a specified SplitMix64 stream from seed.
// The estimator is a Bernoulli mean; variance is unbiased sample
// variance (zero for one sample). Hoeffding confidenceHalfWidth =
// sqrt(log(2/alpha)/(2*N)), the nominal probabilistic bound under ideal IID
// sampling. SplitMix64 is deterministic pseudorandomness, so this is NOT a
// rigorous guarantee for any seed or across seeds. Bounds may exceed [0,1].
[[nodiscard]] std::expected<VisibilityEstimate, SoftShadowError> SampleAreaLightVisibility(
    std::span<DiskBlocker const> blockers, std::uint32_t sampleCount, std::uint64_t seed, float alpha = 0.05F) noexcept;

} // namespace ch38::soft_shadows
